### ISSUE TITLE
Discord Server?

### ISSUE THREAD

**Issue by LeonMarshall** [keycap-archivist/database#169]
I was just going to send a message in the development channel, I clicked send, then suddenly all channels were gone, Or maybe just for me? 

Anyway, My username in discord is skee#5895, My nickname in the server is Leon, I joined in june 2021 and i created 1 or 2 pull requests a while back.

I can't seem to find any other platforms where I can message someone who is definitely in touch with the server to contact, so had to result to github issues, Hopefully you can resolve this? 

![Screenshot_20220417-040357_Discord.jpg](https://user-images.githubusercontent.com/73922854/163698459-ac98f764-e786-4ad8-a518-7f318dcb6c3f.jpg)

**Comment by LeonMarshall** [comment]
I confirm, The discord link now results in expired...

**Comment by zekth** [comment]
contacted via DM
